replicaCount: 1

image:
  repository: ghcr.io/berigny/dualsubstrate
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 50051
  metricsPort: 9090

server:
  port: 50051
  tls:
    enabled: true
    secretName: dualsubstrate-tls
  jwt:
    enabled: false
    audience: ""
    issuer: ""
    pubKeySecret:
      name: ""
      key: public.pem

certificate:
  enabled: true
  secretName: dualsubstrate-tls
  dnsNames:
    - api.dualsubstrate.ai
    - dualsubstrate-grpc.internal
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

gateway:
  cors:
    enabled: true
    allowOrigin: "*"
    allowHeaders:
      - Content-Type
      - Authorization
      - X-Request-ID
    allowMethods:
      - GET
      - POST
      - OPTIONS
  auth:
    enabled: true
    audience: ""
    issuer: ""
    jwksURL: ""

livenessProbe:
  grpc:
    port: 50051
    service: dualsubstrate.v1.Health
  initialDelaySeconds: 10
  periodSeconds: 5

readinessProbe:
  grpc:
    port: 50051
    service: dualsubstrate.v1.Health

resources: {}

serviceMonitor:
  enabled: true
  port: metrics
  path: /metrics
  interval: 15s
  labels:
    release: kube-prometheus-stack

slaAlerts:
  enabled: true
  labels: {}
  annotations: {}
