FROM rust:1.78-alpine AS builder
RUN apk add --no-cache musl-dev openssl-dev
WORKDIR /app
COPY Cargo.toml ./
RUN cargo fetch
COPY src src
COPY gen/openapiv2 gen/openapiv2
RUN cargo build --release --bin gateway

FROM alpine:latest
RUN apk add --no-cache ca-certificates
COPY --from=builder /app/target/release/gateway /gateway
COPY --from=builder /app/gen/openapiv2 /gen/openapiv2
EXPOSE 8080
CMD ["/gateway"]